# Generated by Django 4.2 on 2023-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('bottom_subtitle', models.CharField(max_length=250)),
                ('button_text', models.CharField(max_length=50)),
                ('button_url', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
