# Generated by Django 4.2 on 2023-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('about_title', models.CharField(max_length=100)),
                ('about_desc', models.TextField()),
                ('project_no', models.IntegerField(default=1)),
                ('website_no', models.IntegerField(default=1)),
                ('client_no', models.IntegerField(default=1)),
                ('project_desc', models.CharField(max_length=100)),
                ('website_desc', models.CharField(max_length=100)),
                ('client_desc', models.CharField(max_length=100)),
                ('about_image', models.ImageField(upload_to='settings/')),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('behance', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
